
package rs.bg.ac.student.ivana.MavenClient.form;

import rs.bg.ac.student.ivana.MavenClient.communication.Communication;
import rs.bg.ac.student.ivana.MavenClient.cordinator.Cordinator;
import rs.bg.ac.student.ivana.MavenCommon.domain.Admin;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import javax.swing.JTextField;
import java.awt.Color;
import javax.swing.SwingConstants;

public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMain = new javax.swing.JMenu();
        menuItemClaim = new javax.swing.JMenuItem();
        menuItemClient = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemRiskType = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(51, 51, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblUsername.setBackground(new java.awt.Color(204, 204, 204));
        lblUsername.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("jLabel1");

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenuBar1.setForeground(new java.awt.Color(153, 153, 153));
        jMenuBar1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        menuMain.setText("Menu");

        menuItemClaim.setText("Claim");
        menuMain.add(menuItemClaim);

        menuItemClient.setText("Client");
        menuMain.add(menuItemClient);

        jMenuBar1.add(menuMain);

        jMenu2.setText("Edit");

        menuItemRiskType.setText("RiskType");
        jMenu2.add(menuItemRiskType);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);
        
        JLabel lblNewLabel = new JLabel("Today's exchange rates");
        lblNewLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
        
        txtEUR = new JTextField();
        txtEUR.setColumns(10);
        
        txtUSD = new JTextField();
        txtUSD.setColumns(10);
        
        txtRSD = new JTextField();
        txtRSD.setColumns(10);
        
        lblEUR = new JLabel();
        lblEUR.setText("EUR");
        lblEUR.setHorizontalAlignment(SwingConstants.CENTER);
        lblEUR.setFont(new Font("Consolas", Font.BOLD, 14));
        lblEUR.setBackground(new Color(204, 204, 204));
        
        lblUSD = new JLabel();
        lblUSD.setText("USD");
        lblUSD.setHorizontalAlignment(SwingConstants.CENTER);
        lblUSD.setFont(new Font("Consolas", Font.BOLD, 14));
        lblUSD.setBackground(new Color(204, 204, 204));
        
        lblRSD = new JLabel();
        lblRSD.setText("RSD");
        lblRSD.setHorizontalAlignment(SwingConstants.CENTER);
        lblRSD.setFont(new Font("Consolas", Font.BOLD, 14));
        lblRSD.setBackground(new Color(204, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(155)
        							.addComponent(lblRSD, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createSequentialGroup()
        							.addGap(128)
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        								.addComponent(lblEUR, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
        								.addComponent(lblUSD, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE))
        							.addGap(36)))
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(txtEUR, GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        						.addComponent(txtUSD)
        						.addComponent(txtRSD)))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(69)
        					.addComponent(lblUsername, GroupLayout.PREFERRED_SIZE, 728, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(306)
        					.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 173, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(237, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(29)
        			.addComponent(lblNewLabel)
        			.addGap(30)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtEUR, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblEUR, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE))
        			.addGap(25)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblUSD, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtUSD, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(17)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblRSD, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtRSD, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
        			.addComponent(lblUsername, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        			.addGap(29))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
          try{
        String admin = (String) Cordinator.getInstance().getParam("ADMIN");
            Socket socket = rs.bg.ac.student.ivana.MavenClient.communication.Communication.getInstance().logout(admin);
            socket.close();
            System.exit(0);
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_formWindowClosing

   
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JMenuItem menuItemClaim;
    private javax.swing.JMenuItem menuItemClient;
    private javax.swing.JMenuItem menuItemRiskType;
    private javax.swing.JMenu menuMain;
    private JTextField txtEUR;
    private JTextField txtUSD;
    private JTextField txtRSD;
    private JLabel lblEUR;
    private JLabel lblUSD;
    private JLabel lblRSD;
    // End of variables declaration//GEN-END:variables

    
    
    
    public void addBtnMenuItemClaim(ActionListener actionListener) {
        menuItemClaim.addActionListener(actionListener);
    }

    public void addBtnMenuItemClient(ActionListener actionListener) {
        menuItemClient.addActionListener(actionListener);
    }

    public void addBtnMenuItemRiskType(ActionListener actionListener) {
        menuItemRiskType.addActionListener(actionListener);
    }

    public JLabel getLblUsername() {
        return lblUsername;
    }
    
    public JLabel getLblEUR() {
    	return lblEUR;
    }
    public JLabel getLblUSD() {
    	return lblUSD;
    }
    public JLabel getLblRSD() {
    	return lblRSD;
    }
}
    
    
   
    
    

